services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: pulsepipe
      POSTGRES_PASSWORD: pulsepipe
      POSTGRES_DB: pulsepipe
    ports:
      - "55433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pulsepipe -d pulsepipe"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    command: sh -c "npx prisma generate && npx prisma db push && npm run db:seed && npm run dev"
    environment:
      DATABASE_URL: postgresql://pulsepipe:pulsepipe@postgres:5432/pulsepipe?schema=public
      REDIS_URL: redis://redis:6379
      NEXT_PUBLIC_APP_URL: http://localhost:3002
      RATE_LIMIT_MAX: "120"
      RATE_LIMIT_WINDOW_SECONDS: "60"
      ALLOW_LOCAL_WEBHOOKS: "true"
      DEMO_WEBHOOK_URL: http://app:3000/api/demo/webhook
      DEMO_EMAIL: owner@pulsepipe.dev
      DEMO_PASSWORD: pulsepipe
    ports:
      - "3002:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  worker:
    build: .
    command: sh -c "npx prisma generate && npm run worker"
    environment:
      DATABASE_URL: postgresql://pulsepipe:pulsepipe@postgres:5432/pulsepipe?schema=public
      REDIS_URL: redis://redis:6379
      ALLOW_LOCAL_WEBHOOKS: "true"
      DEMO_WEBHOOK_URL: http://app:3000/api/demo/webhook
      WEBHOOK_TIMEOUT_MS: "8000"
      WORKER_CONCURRENCY: "10"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      app:
        condition: service_started
      redis:
        condition: service_healthy

volumes:
  postgres_data:
